apiVersion: apps/v1
kind: Deployment
metadata:
  name: restro-fastapi
  labels:
    app: restro-fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restro-fastapi
  template:
    metadata:
      labels:
        app: restro-fastapi
    spec:
      containers:
        - name: restro-fastapi
          image: restro_fastapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: ENV
              value: "production"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
