version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: restro
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pRoot@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Migration service - runs once and exits
  migrate:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Root@123
      DATABASE_NAME: restro
    command: uv run alembic upgrade head
    restart: "no"  # Don't restart after completion

  # Main FastAPI service
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: Root@123
      DATABASE_NAME: restro
    restart: unless-stopped

volumes:
  mysql_data: