apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: restro_fastapi:latest
          env:
            - name: DATABASE_HOST
              value: mysql
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_USERNAME
              value: root
            - name: DATABASE_PASSWORD
              value: Root@123
            - name: DATABASE_NAME
              value: restro
          command: ["uv", "run", "alembic", "upgrade", "head"]
      restartPolicy: Never
  backoffLimit: 1
